# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 420ea2e33a736099c6c0dcf792683dd553f34b8ac3ab99403f5394f6249ef8ddd6dec12d4f74144c26b73ac4eec6b0f315512db6160d9f719fbb4411ebb89e75

test:
  secret_key_base: 7c57dd2ac7f57bf735c1d87886904f67296c6c5c9dfc56fb2f3814d2028a066895e815d6846c44fc471da3fe1060c1cdcf92ecc2640334e2e4c9777aacaa4e93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
